# Generated by Django 5.0.3 on 2024-03-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caregiverappointment',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='caregiverappointment',
            name='full_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='caregiverappointment',
            name='phone',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='labserviceappointment',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='labserviceappointment',
            name='full_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='labserviceappointment',
            name='phone',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='transactioncgservice',
            name='payment_medium',
            field=models.CharField(blank=True, choices=[('Esewa', 'Esewa'), ('Khalti', 'Khalti'), ('Cash', 'Cash')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transactionlabservice',
            name='payment_medium',
            field=models.CharField(blank=True, choices=[('Esewa', 'Esewa'), ('Khalti', 'Khalti'), ('Cash', 'Cash')], max_length=50, null=True),
        ),
    ]
