# Generated by Django 5.0.3 on 2024-04-13 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_caregiverappointment_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caregiver',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='caregiverappointment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='labservice',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='labserviceappointment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='transactioncgservice',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='transactionlabservice',
            options={'ordering': ['-created_at']},
        ),
    ]
