# Generated by Django 5.0.3 on 2024-04-18 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_caregiver_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caregiver',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
