# Generated by Django 5.0.3 on 2024-04-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatroom_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='socketauthtoken',
            name='token',
            field=models.TextField(null=True, unique=True),
        ),
    ]
