ESEWA = "Esewa"
KHALTI = "Khalti"
CASH = "Cash"
PAYMENT_MEDIUMS = (
    (ESEWA, ESEWA),
    (KHALTI, KHALTI),
    (CASH, CASH),
)

INITIATED = "Initiated"
VERIFIED = "Verified"
UNVERIFIED = "Unverified"
TRANSACTION_STATUSES = (
    (INITIATED, INITIATED),
    (VERIFIED, VERIFIED),
    (UNVERIFIED, UNVERIFIED)
)
